name: firstwork flow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message
              run: echo "myfirst giworkflow"

            - name: list of files
              run: ls
            - name: read file
              run: cat README.md
              


