name: firstwork flow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4.2.2
            #- name: Welcome message
            #  run: echo "myfirst giworkflow"

            - name : list and read file
              run:
                echo "MY first GITHB action JOB"
                ls -ltra
                cat README.md

            - name : Geneerate ASCII artwork
              run: cowsay -f dragon "Run for cover, I am a DRAGON ............RAWR" >> dragon.txt


           # - name: list of files
           #   run: ls
           # - name: read file
           #   run: cat README.md



