name: mutli job workflow

on: push

jobs: 
    first_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4.2.2
            #- name: Welcome message
            #  run: echo "myfirst giworkflow"

            - name : list and read file
              run:  |
                echo "MY first GITHB action JOB"
                ls -ltra
                cat README.md

            - name: Install cowsay program
              run: sudo apt-get install cowsay -y

            
            - name : Geneerate ASCII artwork
              run: cowsay -f dragon "Run for cover, I am a DRAGON ............RAWR" >> dragon.txt

            - name : read the file 
              run: ls -ltra

            - name: upload dragon text file
              uses: actions/upload-artifact@v4
              with:
                name: dragon-txt-file
                path: dragon.txt


    test_jobs_2:
        needs: first_job_1
        runs-on: ubuntu-latest
        steps:

            - name: download dragon text file
              uses: actions/download-artifact@v4
              with:
                name: dragon-txt-file
                

            - name: Test File exists
              run: grep -i "dragon" dragon.txt


    test_jobs_3:
        needs: [test_jobs_2]
        runs-on: ubntu-latest
        steps:

            - name: download dragon text file
              uses: actions/download-artifact@v4
              with:
                name: dragon-txt-file  
            
                
            - name: Test File exists
              run: grep -i "dragon" dragon.txt
                
            #- name: Read file
            #  run: cat dragon.txt

            - name: Deploy
              run: echo Deploying .......................................

              
              